"""Feature tag filters for face/hand crops.

These are used to filter out tags that clearly do not belong to a feature crop.
"""

from __future__ import annotations

import re

FACE_TAG_BLACKLIST = {
    "abs",
    "back",
    "backpack",
    "background",
    "bed",
    "bikini",
    "boots",
    "bra",
    "building",
    "car",
    "city",
    "cloud",
    "coat",
    "dress",
    "feet",
    "feet out of frame",
    "floor",
    "forest",
    "grass",
    "hand",
    "hands",
    "hat",
    "house",
    "indoor",
    "jacket",
    "kitchen",
    "legs",
    "legs up",
    "landscape",
    "mountain",
    "outdoor",
    "pants",
    "park",
    "pool",
    "road",
    "scenery",
    "shirt",
    "shoes",
    "shorts",
    "skirt",
    "sky",
    "street",
    "table",
    "tattoo",
    "tree",
    "upper body",
    "window",
}

HAND_TAG_BLACKLIST = {
    "abs",
    "age",
    "back",
    "bare shoulders",
    "bare shoulders",
    "bathroom",
    "bed",
    "black hair",
    "blonde hair",
    "blue eyes",
    "blurry",
    "blush",
    "bikini",
    "blue eyes",
    "brown hair",
    "blush",
    "cheek",
    "cheekbones",
    "chin",
    "bra",
    "brown eyes",
    "building",
    "coat",
    "collarbone",
    "city",
    "ear",
    "earrings",
    "eyebrows",
    "eye contact",
    "cleavage",
    "eye focus",
    "cloud",
    "dress",
    "eyewear",
    "eyebrows",
    "face paint",
    "eyes",
    "facial hair",
    "fangs",
    "freckles",
    "full body",
    "eyelashes",
    "green hair",
    "eyeshadow",
    "hair bun",
    "hair ornament",
    "hair over one eye",
    "hair pulled back",
    "face",
    "head",
    "head tilt",
    "headband",
    "helmet",
    "hips",
    "hood",
    "facial",
    "jacket",
    "flux chin",
    "knees",
    "kneeling",
    "legs",
    "legs up",
    "long hair",
    "long sleeves",
    "full body",
    "lipstick",
    "lipstick tube",
    "green eyes",
    "looking away",
    "looking back",
    "looking down",
    "looking to the side",
    "looking up",
    "makeup",
    "mask",
    "messy hair",
    "mouth",
    "open mouth",
    "hair",
    "neck",
    "necklace",
    "nipples",
    "navel",
    "one eye closed",
    "hat",
    "pants",
    "indoors",
    "pantyhose",
    "ponytail",
    "portrait",
    "kitchen",
    "red hair",
    "red lips",
    "red shirt",
    "red dress",
    "ribbon",
    "lips",
    "short hair",
    "short sleeves",
    "looking at the camera",
    "shorts",
    "skirt",
    "smile",
    "nose",
    "socks",
    "standing",
    "stomach",
    "sweater",
    "sweater dress",
    "swimsuit",
    "outdoors",
    "panties",
    "pussy",
    "thighs",
    "thigh-high socks",
    "t-shirt",
    "tongue",
    "shirt",
    "waist",
    "white hair",
    "window",
    "yellow hair",
    "shoes",
    "sky",
    "street",
    "table",
    "teeth",
    "tongue",
    "upper body",
}

FACE_TAG_ALLOWLIST_PATTERNS = [
    r"face",
    r"head",
    r"eye",
    r"eyebrow",
    r"eyelash",
    r"eyeshadow",
    r"eyewear",
    r"lip",
    r"lipstick",
    r"mouth",
    r"teeth",
    r"tongue",
    r"nose",
    r"nostril",
    r"cheek",
    r"chin",
    r"jaw",
    r"beard",
    r"mustache",
    r"moustache",
    r"ear",
    r"earring",
    r"hair",
    r"bangs",
    r"hairstyle",
    r"freckle",
    r"wrinkle",
    r"scar",
    r"blush",
    r"makeup",
    r"mascara",
    r"smile",
    r"grin",
    r"expression",
    r"tears",
    r"yawn",
    r"yawning",
    r"glasses",
    r"goggles",
    r"mask",
    r"helmet",
    r"hood",
    r"hat",
    r"looking",
    r"face paint",
]

HAND_TAG_ALLOWLIST_PATTERNS = [
    r"hand",
    r"digit",
    r"finger",
    r"fingers",
    r"fingernail",
    r"nail",
    r"nails",
    r"thumb",
    r"palm",
    r"wrist",
    r"knuckle",
    r"fist",
    r"glove",
    r"gloves",
    r"ring",
    r"bracelet",
    r"wristband",
    r"watch",
]


def _compile(patterns: list[str]) -> re.Pattern[str]:
    return re.compile("(" + "|".join(patterns) + ")", re.IGNORECASE)


_FACE_ALLOW_RE = _compile(FACE_TAG_ALLOWLIST_PATTERNS)
_HAND_ALLOW_RE = _compile(HAND_TAG_ALLOWLIST_PATTERNS)


def is_face_tag(tag: str) -> bool:
    if not tag:
        return False
    if tag in FACE_TAG_BLACKLIST:
        return False
    return bool(_FACE_ALLOW_RE.search(tag))


def is_hand_tag(tag: str) -> bool:
    if not tag:
        return False
    if tag in HAND_TAG_BLACKLIST:
        return False
    return bool(_HAND_ALLOW_RE.search(tag))
