# tag_natural_map.py
# Mapping of WD14/booru-style tags to natural language phrases for semantic search
# Extend or edit as needed for your dataset

tag_natural_map = {
    # Common tags
    "1girl": "a woman",
    "1boy": "a man",
    "solo": "alone",
    "smile": "smiling",
    "blush": "blushing",
    "long_hair": "long hair",
    "short_hair": "short hair",
    "blue_eyes": "blue eyes",
    "brown_eyes": "brown eyes",
    "green_eyes": "green eyes",
    "red_eyes": "red eyes",
    "blonde_hair": "blonde hair",
    "brown_hair": "brown hair",
    "black_hair": "black hair",
    "pink_hair": "pink hair",
    "purple_hair": "purple hair",
    "white_hair": "white hair",
    "looking_at_viewer": "looking at the camera",
    "open_mouth": "open mouth",
    "closed_mouth": "closed mouth",
    "bangs": "bangs",
    "skirt": "skirt",
    "dress": "dress",
    "shirt": "shirt",
    "jacket": "jacket",
    "hat": "hat",
    "gloves": "gloves",
    "ribbon": "ribbon",
    "bow": "bow",
    "flower": "flower",
    "animal_ears": "animal ears",
    "tail": "tail",
    "sitting": "sitting",
    "standing": "standing",
    "outdoors": "outdoors",
    "indoors": "indoors",
    "upper_body": "upper body",
    "full_body": "full body",
    "simple_background": "simple background",
    "white_background": "white background",
    "holding": "holding something",
    "smiling": "smiling",
    "blushing": "blushing",
    # Add more as needed
}
