"""make names required

Revision ID: 0beaf9bc3c44
Revises: f9fba6945601
Create Date: 2026-01-23 21:11:04.120189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0beaf9bc3c44"
down_revision: Union[str, None] = "f9fba6945601"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE character SET name='Unknown' WHERE name IS NULL")
    op.execute("UPDATE pictureset SET name='Untitled' WHERE name IS NULL")
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
    with op.batch_alter_table("pictureset", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pictureset", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
