"""initial schema

Revision ID: f9fba6945601
Revises: 
Create Date: 2026-01-23 20:21:20.640407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9fba6945601'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('schema_version')
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('image_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=True),
    sa.Column('thumbnail_left', sa.Integer(), nullable=True),
    sa.Column('thumbnail_top', sa.Integer(), nullable=True),
    sa.Column('thumbnail_side', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('aesthetic_score', sa.Float(), nullable=True),
    sa.Column('pixel_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picture_pixel_sha'), ['pixel_sha'], unique=False)

    op.create_table('pictureset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pictureset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pictureset_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descending', sa.Boolean(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('show_stars', sa.Boolean(), nullable=False),
    sa.Column('similarity_character', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_picture_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reference_picture_set_id'], ['pictureset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_name'), ['name'], unique=False)

    op.create_table('picturelikeness',
    sa.Column('picture_id_a', sa.Integer(), nullable=False),
    sa.Column('picture_id_b', sa.Integer(), nullable=False),
    sa.Column('likeness', sa.Float(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('picture_id_a < picture_id_b', name='ck_picture_pair_order'),
    sa.ForeignKeyConstraint(['picture_id_a'], ['picture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picture_id_b'], ['picture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('picture_id_a', 'picture_id_b')
    )
    with op.batch_alter_table('picturelikeness', schema=None) as batch_op:
        batch_op.create_index('ix_picture_likeness_a', ['picture_id_a'], unique=False)
        batch_op.create_index('ix_picture_likeness_b', ['picture_id_b'], unique=False)
        batch_op.create_index(batch_op.f('ix_picturelikeness_picture_id_a'), ['picture_id_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_picturelikeness_picture_id_b'), ['picture_id_b'], unique=False)

    op.create_table('picturelikenessfrontier',
    sa.Column('picture_id_a', sa.Integer(), nullable=False),
    sa.Column('j_max', sa.Integer(), nullable=False),
    sa.CheckConstraint('j_max >= picture_id_a', name='ck_frontier_order'),
    sa.ForeignKeyConstraint(['picture_id_a'], ['picture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('picture_id_a')
    )
    with op.batch_alter_table('picturelikenessfrontier', schema=None) as batch_op:
        batch_op.create_index('ix_picture_frontier_a', ['picture_id_a'], unique=False)

    op.create_table('picturesetmember',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['pictureset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'picture_id')
    )
    with op.batch_alter_table('picturesetmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picturesetmember_picture_id'), ['picture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picturesetmember_set_id'), ['set_id'], unique=False)

    op.create_table('tag',
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('picture_id', 'tag')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_picture_id'), ['picture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_tag'), ['tag'], unique=False)

    op.create_table('usertoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usertoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usertoken_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_usertoken_user_id'), ['user_id'], unique=False)

    op.create_table('face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('face_index', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.Column('features', sa.LargeBinary(), nullable=True),
    sa.Column('likeness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picture_id', 'frame_index', 'face_index')
    )
    with op.batch_alter_table('face', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_character_id'), ['character_id'], unique=False)

    op.create_table('facecharacterlikeness',
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('likeness', sa.Float(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['face_id'], ['face.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('face_id', 'character_id')
    )
    with op.batch_alter_table('facecharacterlikeness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facecharacterlikeness_likeness'), ['likeness'], unique=False)

    op.create_table('facelikeness',
    sa.Column('face_id_a', sa.Integer(), nullable=False),
    sa.Column('face_id_b', sa.Integer(), nullable=False),
    sa.Column('likeness', sa.Float(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('face_id_a < face_id_b', name='ck_face_pair_order'),
    sa.ForeignKeyConstraint(['face_id_a'], ['face.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['face_id_b'], ['face.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('face_id_a', 'face_id_b')
    )
    with op.batch_alter_table('facelikeness', schema=None) as batch_op:
        batch_op.create_index('ix_face_likeness_a', ['face_id_a'], unique=False)
        batch_op.create_index('ix_face_likeness_b', ['face_id_b'], unique=False)
        batch_op.create_index(batch_op.f('ix_facelikeness_likeness'), ['likeness'], unique=False)

    op.create_table('facelikenessfrontier',
    sa.Column('face_id_a', sa.Integer(), nullable=False),
    sa.Column('j_max', sa.Integer(), nullable=False),
    sa.CheckConstraint('j_max >= face_id_a', name='ck_frontier_order'),
    sa.ForeignKeyConstraint(['face_id_a'], ['face.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('face_id_a')
    )
    with op.batch_alter_table('facelikenessfrontier', schema=None) as batch_op:
        batch_op.create_index('ix_face_frontier_a', ['face_id_a'], unique=False)

    op.create_table('quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.Column('face_id', sa.Integer(), nullable=True),
    sa.Column('sharpness', sa.Float(), nullable=True),
    sa.Column('edge_density', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.Column('color_histogram', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['face_id'], ['face.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_brightness'), ['brightness'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_contrast'), ['contrast'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_edge_density'), ['edge_density'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_face_id'), ['face_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_noise_level'), ['noise_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_picture_id'), ['picture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_sharpness'), ['sharpness'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_sharpness'))
        batch_op.drop_index(batch_op.f('ix_quality_picture_id'))
        batch_op.drop_index(batch_op.f('ix_quality_noise_level'))
        batch_op.drop_index(batch_op.f('ix_quality_face_id'))
        batch_op.drop_index(batch_op.f('ix_quality_edge_density'))
        batch_op.drop_index(batch_op.f('ix_quality_contrast'))
        batch_op.drop_index(batch_op.f('ix_quality_brightness'))

    op.drop_table('quality')
    with op.batch_alter_table('facelikenessfrontier', schema=None) as batch_op:
        batch_op.drop_index('ix_face_frontier_a')

    op.drop_table('facelikenessfrontier')
    with op.batch_alter_table('facelikeness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facelikeness_likeness'))
        batch_op.drop_index('ix_face_likeness_b')
        batch_op.drop_index('ix_face_likeness_a')

    op.drop_table('facelikeness')
    with op.batch_alter_table('facecharacterlikeness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facecharacterlikeness_likeness'))

    op.drop_table('facecharacterlikeness')
    with op.batch_alter_table('face', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_character_id'))

    op.drop_table('face')
    with op.batch_alter_table('usertoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usertoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_usertoken_token_hash'))

    op.drop_table('usertoken')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_tag'))
        batch_op.drop_index(batch_op.f('ix_tag_picture_id'))

    op.drop_table('tag')
    with op.batch_alter_table('picturesetmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picturesetmember_set_id'))
        batch_op.drop_index(batch_op.f('ix_picturesetmember_picture_id'))

    op.drop_table('picturesetmember')
    with op.batch_alter_table('picturelikenessfrontier', schema=None) as batch_op:
        batch_op.drop_index('ix_picture_frontier_a')

    op.drop_table('picturelikenessfrontier')
    with op.batch_alter_table('picturelikeness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picturelikeness_picture_id_b'))
        batch_op.drop_index(batch_op.f('ix_picturelikeness_picture_id_a'))
        batch_op.drop_index('ix_picture_likeness_b')
        batch_op.drop_index('ix_picture_likeness_a')

    op.drop_table('picturelikeness')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_name'))

    op.drop_table('character')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('pictureset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pictureset_name'))

    op.drop_table('pictureset')
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picture_pixel_sha'))

    op.drop_table('picture')
    op.drop_table('metadata')
    # ### end Alembic commands ###
