import sqlite3
import sys
import os


def reset_embeddings(db_path):
    if not os.path.exists(db_path):
        print(f"Error: Database not found at {db_path}")
        return

    conn = sqlite3.connect(db_path)
    try:
        cursor = conn.cursor()

        # 1. Clear Image Embeddings, Text Embeddings, and Aesthetic Scores
        # We clear aesthetic scores because they are generated by the CLIP model
        # and we want to ensure they represent the new V2 model quality.
        print("Clearing image_embedding, text_embedding, and aesthetic_score...")
        cursor.execute("""
            UPDATE picture 
            SET image_embedding = NULL, 
                text_embedding = NULL, 
                aesthetic_score = NULL
        """)

        rows = cursor.rowcount
        conn.commit()
        print(f"Reset embeddings and scores for {rows} pictures.")

        # Optional: Vacuum to reclaim space since embeddings are large blobs
        print("Vacuuming database (this might take a moment)...")
        conn.execute("VACUUM")
        print("Done.")

    except Exception as e:
        print(f"Error: {e}")
        conn.rollback()
    finally:
        conn.close()


if __name__ == "__main__":
    target_db = None

    if len(sys.argv) >= 2:
        target_db = sys.argv[1]
    elif os.path.exists("vault.db"):
        target_db = "vault.db"
        print(f"Using default database: {target_db}")

    if target_db:
        reset_embeddings(target_db)
    else:
        print("Error: Could not find vault.db and no path provided.")
        print(f"Usage: python {sys.argv[0]} <path_to_vault.db>")
        sys.exit(1)
